services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: docsf_frontend_production:latest
    container_name: docsf_frontend_production
    ports:
      - "0.0.0.0:3000:3000"
    env_file:
      - .env.production
    restart: always

volumes:
  db_data: