services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: crm:latest
    container_name: crm
    ports:
      - '0.0.0.0:3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    restart: always

volumes:
  db_data:
